#!/usr/bin/env python

from dbmarshal import DBMarshal
import sys

def usage():
    print 'Usage:\ndbmarshal init hostname username password database migrations-directory alias'
    exit(1)

if len(sys.argv) < 2:
    usage()
elif sys.argv[1] == 'init':
    if len(sys.argv) < 8:
        usage()

    DBMarshal.create_alias(sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5], sys.argv[6], sys.argv[7])
    print "\n"

elif len(sys.argv) >= 2:

    if hasattr(DBMarshal, sys.argv[1]):
        dbm = DBMarshal.from_alias('default')
        action = sys.argv[1]
        start_args = 2
    else:
        dbm = DBMarshal.from_alias(sys.argv[1])
        action = sys.argv[2]
        start_args = 3


    if hasattr(dbm, action):
        params = sys.argv[start_args:len(sys.argv)]

        getattr(dbm, action)(*params)

        print "\n"

    else:
        usage()
else:
    usage()