#!/bin/bash

chmod +x dbmarshal

if ! sudo apt-get install python python-mysqldb python-setuptools
then
    exit 1
fi

if ! sudo easy_install pip
then
    exit 1
fi

if ! sudo pip install sqlparse
then
    exit 1
fi

mydir=`pwd`
pathline="PATH=\"$mydir:\$PATH\""
temp=`grep -v "$pathline" ~/.bashrc`
echo -e "$temp" > ~/.bashrc
echo "$pathline" >> ~/.bashrc
echo "export PATH" >> ~/.bashrc
source ~/.bashrc
echo
echo "Finished installing dbmarshal."
