#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
pwd

chmod +x dbmarshal

if ! sudo apt-get install python python-mysqldb python-setuptools -y
then
    exit 1
fi

if ! sudo easy_install pip
then
    exit 1
fi

if ! sudo pip install sqlparse
then
    exit 1
fi

mydir=`pwd`
sudo ln -s "$mydir/dbmarshal" "/usr/bin/dbmarshal"
echo
echo "Finished installing dbmarshal."
